# -*- coding: utf-8 -*-
"""Comparemodelsforcsvdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdjjuA_N8wQ6_SrrN7b0iZYCovyv-bJj

# **First-Ml-project**

#**Importing Data**
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/delaney_solubility_with_descriptors.csv')
df

"""#**Making the data information**

### **Separate the output and inputs  , your x and y**
"""

y = df.iloc[:, -1]
x = df.iloc[:, :-1]

"""###**SpLit data  , that is, training and test data**"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 100)

"""#**Building the model**

### **We use linear models to check if solubility can be explained by a linear relationship with molecular descriptors.**
"""

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, BayesianRidge, HuberRegressor, SGDRegressor, PassiveAggressiveRegressor

lr_model1 = LinearRegression()
lr_model2 = Ridge()
lr_model3 = Lasso()
lr_model4 = ElasticNet()
lr_model5 = BayesianRidge()
lr_model6 = HuberRegressor()
lr_model7 = SGDRegressor()
lr_model8 = PassiveAggressiveRegressor()

lr_model1.fit(x_train, y_train)
lr_model2.fit(x_train, y_train)
lr_model3.fit(x_train, y_train)
lr_model4.fit(x_train, y_train)
lr_model5.fit(x_train, y_train)
lr_model6.fit(x_train, y_train)
lr_model7.fit(x_train, y_train)
lr_model8.fit(x_train, y_train)

"""##**Testing predictions**"""

##**Testing predictions**

y_pred_Model1_train = lr_model1.predict(x_train)
y_pred_Model1_test = lr_model1.predict(x_test)

y_pred_Model2_train = lr_model2.predict(x_train)
y_pred_Model2_test = lr_model2.predict(x_test)

y_pred_Model3_train = lr_model3.predict(x_train)
y_pred_Model3_test = lr_model3.predict(x_test)

y_pred_Model4_train = lr_model4.predict(x_train)
y_pred_Model4_test = lr_model4.predict(x_test)

y_pred_Model5_train = lr_model5.predict(x_train)
y_pred_Model5_test = lr_model5.predict(x_test)

y_pred_Model6_train = lr_model6.predict(x_train)
y_pred_Model6_test = lr_model6.predict(x_test)

y_pred_Model7_train = lr_model7.predict(x_train)
y_pred_Model7_test = lr_model7.predict(x_test)

y_pred_Model8_train = lr_model8.predict(x_train)
y_pred_Model8_test = lr_model8.predict(x_test)


from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

models = ["Linear", "Ridge", "Lasso", "ElasticNet", "Bayesian", "Huber", "SGD", "PassiveAggressive"]

train_mse = []
test_mse = []

train_mae = []
test_mae = []

train_r2 = []
test_r2 = []



# Model 1
train_mse.append(mean_squared_error(y_train, y_pred_Model1_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model1_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model1_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model1_test))

train_r2.append(r2_score(y_train, y_pred_Model1_train))
test_r2.append(r2_score(y_test, y_pred_Model1_test))

# Model 2
train_mse.append(mean_squared_error(y_train, y_pred_Model2_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model2_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model2_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model2_test))

train_r2.append(r2_score(y_train, y_pred_Model2_train))
test_r2.append(r2_score(y_test, y_pred_Model2_test))

# Model 3
train_mse.append(mean_squared_error(y_train, y_pred_Model3_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model3_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model3_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model3_test))

train_r2.append(r2_score(y_train, y_pred_Model3_train))
test_r2.append(r2_score(y_test, y_pred_Model3_test))

# Model 4
train_mse.append(mean_squared_error(y_train, y_pred_Model4_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model4_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model4_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model4_test))

train_r2.append(r2_score(y_train, y_pred_Model4_train))
test_r2.append(r2_score(y_test, y_pred_Model4_test))

# Model 5
train_mse.append(mean_squared_error(y_train, y_pred_Model5_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model5_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model5_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model5_test))

train_r2.append(r2_score(y_train, y_pred_Model5_train))
test_r2.append(r2_score(y_test, y_pred_Model5_test))

# Model 6
train_mse.append(mean_squared_error(y_train, y_pred_Model6_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model6_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model6_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model6_test))

train_r2.append(r2_score(y_train, y_pred_Model6_train))
test_r2.append(r2_score(y_test, y_pred_Model6_test))

# Model 7
train_mse.append(mean_squared_error(y_train, y_pred_Model7_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model7_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model7_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model7_test))

train_r2.append(r2_score(y_train, y_pred_Model7_train))
test_r2.append(r2_score(y_test, y_pred_Model7_test))

# Model 8
train_mse.append(mean_squared_error(y_train, y_pred_Model8_train))
test_mse.append(mean_squared_error(y_test, y_pred_Model8_test))

train_mae.append(mean_absolute_error(y_train, y_pred_Model8_train))
test_mae.append(mean_absolute_error(y_test, y_pred_Model8_test))

train_r2.append(r2_score(y_train, y_pred_Model8_train))
test_r2.append(r2_score(y_test, y_pred_Model8_test))

"""##**Compare predictions with actual values**"""

import numpy as np

mse_diff = np.abs(np.array(train_mse) - np.array(test_mse))
mae_diff = np.abs(np.array(train_mae) - np.array(test_mae))
r2_diff = np.abs(np.array(train_r2) - np.array(test_r2))

results_df = pd.DataFrame({
    'Model': ['Linear', 'Ridge', 'Lasso', 'ElasticNet', 'BayesianRidge', 'Huber', 'SGD', 'PassiveAggressive'],

    'Train_R2': [f"{r2:.4f}" for r2 in train_r2],
    'Test_R2': [f"{r2:.4f}" for r2 in test_r2],
    'R2_Diff': [f"{diff:.4f}" for diff in r2_diff],

    'Train_MSE': [f"{mse:.4f}" for mse in train_mse],
    'Test_MSE': [f"{mse:.4f}" for mse in test_mse],
    'MSE_Diff': [f"{diff:.4f}" for diff in mse_diff],

    'Train_MAE': [f"{mae:.4f}" for mae in train_mae],
    'Test_MAE': [f"{mae:.4f}" for mae in test_mae],
    'MAE_Diff': [f"{diff:.4f}" for diff in mae_diff]
})

best_idx = np.argmax(test_r2)
best_model = results_df.iloc[best_idx]['Model']
best_test_r2 = float(results_df.iloc[best_idx]['Test_R2'])
best_test_mse = float(results_df.iloc[best_idx]['Test_MSE'])
best_test_mae = float(results_df.iloc[best_idx]['Test_MAE'])

ideal_r2 = 0.85
ideal_mse = 0.40
ideal_mae = 0.50

# Print the table
print("\n" + "="*120)
print(" " * 40 + "COMPREHENSIVE MODEL EVALUATION TABLE")
print("="*120)
print("\n📊 NOTE: Train metrics = Predictions on training data (shows how well model learned)")
print("         Test metrics = Predictions on unseen test data (shows real performance)")
print("         Diff = Absolute difference between Train and Test (lower = less overfitting)")
print("\n" + "="*120)

from tabulate import tabulate
print(tabulate(results_df, headers='keys', tablefmt='grid', showindex=False))

print("\n" + "="*120)
print(f"\n🏆 BEST MODEL: {best_model}")
print("="*40)
print(f"   • Test R² Score: {best_test_r2:.4f} (Ideal: > {ideal_r2})")
print(f"   • Test MSE: {best_test_mse:.4f} (Ideal: < {ideal_mse})")
print(f"   • Test MAE: {best_test_mae:.4f} (Ideal: < {ideal_mae})")
print("\n" + "="*120)